# Generated by Django 2.2.4 on 2019-08-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name.', max_length=50)),
                ('description', models.CharField(help_text='Enter the product description.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the product price.', max_digits=5)),
                ('category', models.CharField(help_text='Enter the product category.', max_length=50)),
            ],
        ),
    ]
